plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.4'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.dolijo'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
	maven { url 'https://repo.spring.io/snapshot' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'com.mysql:mysql-connector-j'
	annotationProcessor 'org.projectlombok:lombok'
	//Querydsl start
	implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
	annotationProcessor "com.querydsl:querydsl-apt:" + "${dependencyManagement.importedProperties['querydsl.version']}:jakarta"
	annotationProcessor "jakarta.annotation:jakarta.annotation-api"
	annotationProcessor "jakarta.persistence:jakarta.persistence-api"
	//Querydsl end

	// swagger
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0'

	//spring ai
//	implementation platform("org.springframework.ai:spring-ai-bom:1.0.0-SNAPSHOT")
//	implementation 'org.springframework.ai:spring-ai-openai'

	// spring ai - spring boot starter
	// Spring AI BOM (안정판)
	implementation platform("org.springframework.ai:spring-ai-bom:1.0.1")
	// OpenAI 스타터 (ChatClient 자동구성)
	implementation "org.springframework.ai:spring-ai-starter-model-openai"
	// (이미 있는 것들은 유지)
	implementation 'org.springframework.boot:spring-boot-starter-web'


	// spring batch
	implementation 'org.springframework.boot:spring-boot-starter-batch'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	// firebase push
	implementation 'com.google.firebase:firebase-admin:9.5.0'
	// 테스트 코드에도 lombok 적용
	testCompileOnly 'org.projectlombok:lombok'
	testAnnotationProcessor'org.projectlombok:lombok'

	implementation 'io.jsonwebtoken:jjwt-api:0.12.3'
	implementation 'io.jsonwebtoken:jjwt-impl:0.12.3'
	implementation 'io.jsonwebtoken:jjwt-jackson:0.12.3'

}

tasks.named('test') {
	useJUnitPlatform()
}
